# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multi_ring_buffer_dialog_base.ui'
#
# Created: Tue Jul 21 22:46:29 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(418, 243)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        self.label_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.buffer_layer_name = QtGui.QLabel(self.tab)
        self.buffer_layer_name.setMinimumSize(QtCore.QSize(150, 0))
        self.buffer_layer_name.setObjectName(_fromUtf8("buffer_layer_name"))
        self.horizontalLayout_4.addWidget(self.buffer_layer_name)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(130, 0))
        self.label.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.bufferDistance = QtGui.QDoubleSpinBox(self.tab)
        self.bufferDistance.setMinimumSize(QtCore.QSize(150, 0))
        self.bufferDistance.setDecimals(10)
        self.bufferDistance.setMaximum(999999999.99)
        self.bufferDistance.setObjectName(_fromUtf8("bufferDistance"))
        self.horizontalLayout.addWidget(self.bufferDistance)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.segmentsToApproximate = QtGui.QSpinBox(self.tab)
        self.segmentsToApproximate.setMinimumSize(QtCore.QSize(150, 0))
        self.segmentsToApproximate.setMaximum(300)
        self.segmentsToApproximate.setProperty("value", 25)
        self.segmentsToApproximate.setObjectName(_fromUtf8("segmentsToApproximate"))
        self.horizontalLayout_2.addWidget(self.segmentsToApproximate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.numberOfRings = QtGui.QSpinBox(self.tab)
        self.numberOfRings.setMinimumSize(QtCore.QSize(150, 0))
        self.numberOfRings.setMaximum(999999999)
        self.numberOfRings.setProperty("value", 5)
        self.numberOfRings.setObjectName(_fromUtf8("numberOfRings"))
        self.horizontalLayout_3.addWidget(self.numberOfRings)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.selectedfeats = QtGui.QCheckBox(self.tab)
        self.selectedfeats.setEnabled(True)
        self.selectedfeats.setChecked(False)
        self.selectedfeats.setObjectName(_fromUtf8("selectedfeats"))
        self.verticalLayout.addWidget(self.selectedfeats)
        self.dissovle_button_2 = QtGui.QCheckBox(self.tab)
        self.dissovle_button_2.setChecked(True)
        self.dissovle_button_2.setObjectName(_fromUtf8("dissovle_button_2"))
        self.verticalLayout.addWidget(self.dissovle_button_2)
        spacerItem = QtGui.QSpacerItem(373, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sequential_style = QtGui.QRadioButton(self.tab_2)
        self.sequential_style.setChecked(True)
        self.sequential_style.setObjectName(_fromUtf8("sequential_style"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.sequential_style)
        self.horizontalLayout_5.addWidget(self.sequential_style)
        self.central_style = QtGui.QRadioButton(self.tab_2)
        self.central_style.setObjectName(_fromUtf8("central_style"))
        self.buttonGroup.addButton(self.central_style)
        self.horizontalLayout_5.addWidget(self.central_style)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Multi Ring Buffer", None))
        self.label_4.setText(_translate("Dialog", "Layer to be buffered:", None))
        self.buffer_layer_name.setToolTip(_translate("Dialog", "Please select layer from the layers panel befopre buffering to change.", None))
        self.buffer_layer_name.setText(_translate("Dialog", "<html><head/><body><p>No layer found</p></body></html>", None))
        self.label.setText(_translate("Dialog", "Buffer Distance", None))
        self.bufferDistance.setToolTip(_translate("Dialog", "Buffer distance in your selected layers CRS units.", None))
        self.label_2.setText(_translate("Dialog", "Segments to Approximate", None))
        self.segmentsToApproximate.setToolTip(_translate("Dialog", "How smooth the resulting buffers will be.", None))
        self.label_3.setText(_translate("Dialog", "Number of Rings", None))
        self.numberOfRings.setToolTip(_translate("Dialog", "Number of rings.", None))
        self.selectedfeats.setText(_translate("Dialog", "Buffer only selected features", None))
        self.dissovle_button_2.setToolTip(_translate("Dialog", "Not dissolving may produce strange results with neighbouring features.", None))
        self.dissovle_button_2.setText(_translate("Dialog", "Dissolve features before buffering.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Settings", None))
        self.label_5.setText(_translate("Dialog", "Buffer style:", None))
        self.sequential_style.setToolTip(_translate("Dialog", "Buffer resulting buffer sequentially.", None))
        self.sequential_style.setText(_translate("Dialog", "Sequential", None))
        self.central_style.setToolTip(_translate("Dialog", "Buffer the central feature with increasing distance.", None))
        self.central_style.setText(_translate("Dialog", "Central", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://rawgit.com/HeikkiVesanto/QGIS_Multi_Ring_Buffer/master/help/index.html\"><span style=\" text-decoration: underline; color:#0000ff;\">What does this mean?</span></a></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Advanced", None))

