# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multi_ring_buffer_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 243)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        self.label_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.buffer_layer_name = QtWidgets.QLabel(self.tab)
        self.buffer_layer_name.setMinimumSize(QtCore.QSize(150, 0))
        self.buffer_layer_name.setObjectName("buffer_layer_name")
        self.horizontalLayout_4.addWidget(self.buffer_layer_name)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(130, 0))
        self.label.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.bufferDistance = QtWidgets.QDoubleSpinBox(self.tab)
        self.bufferDistance.setMinimumSize(QtCore.QSize(150, 0))
        self.bufferDistance.setDecimals(10)
        self.bufferDistance.setMaximum(999999999.99)
        self.bufferDistance.setObjectName("bufferDistance")
        self.horizontalLayout.addWidget(self.bufferDistance)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.segmentsToApproximate = QtWidgets.QSpinBox(self.tab)
        self.segmentsToApproximate.setMinimumSize(QtCore.QSize(150, 0))
        self.segmentsToApproximate.setMaximum(300)
        self.segmentsToApproximate.setProperty("value", 25)
        self.segmentsToApproximate.setObjectName("segmentsToApproximate")
        self.horizontalLayout_2.addWidget(self.segmentsToApproximate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.numberOfRings = QtWidgets.QSpinBox(self.tab)
        self.numberOfRings.setMinimumSize(QtCore.QSize(150, 0))
        self.numberOfRings.setMaximum(999999999)
        self.numberOfRings.setProperty("value", 5)
        self.numberOfRings.setObjectName("numberOfRings")
        self.horizontalLayout_3.addWidget(self.numberOfRings)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.selectedfeats = QtWidgets.QCheckBox(self.tab)
        self.selectedfeats.setEnabled(True)
        self.selectedfeats.setChecked(False)
        self.selectedfeats.setObjectName("selectedfeats")
        self.verticalLayout.addWidget(self.selectedfeats)
        self.dissovle_button_2 = QtWidgets.QCheckBox(self.tab)
        self.dissovle_button_2.setChecked(True)
        self.dissovle_button_2.setObjectName("dissovle_button_2")
        self.verticalLayout.addWidget(self.dissovle_button_2)
        spacerItem = QtWidgets.QSpacerItem(373, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sequential_style = QtWidgets.QRadioButton(self.tab_2)
        self.sequential_style.setChecked(True)
        self.sequential_style.setObjectName("sequential_style")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.sequential_style)
        self.horizontalLayout_5.addWidget(self.sequential_style)
        self.central_style = QtWidgets.QRadioButton(self.tab_2)
        self.central_style.setObjectName("central_style")
        self.buttonGroup.addButton(self.central_style)
        self.horizontalLayout_5.addWidget(self.central_style)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Multi Ring Buffer"))
        self.label_4.setText(_translate("Dialog", "Layer to be buffered:"))
        self.buffer_layer_name.setToolTip(_translate("Dialog", "Please select layer from the layers panel befopre buffering to change."))
        self.buffer_layer_name.setText(_translate("Dialog", "<html><head/><body><p>No layer found</p></body></html>"))
        self.label.setText(_translate("Dialog", "Buffer Distance"))
        self.bufferDistance.setToolTip(_translate("Dialog", "Buffer distance in your selected layers CRS units."))
        self.label_2.setText(_translate("Dialog", "Segments to Approximate"))
        self.segmentsToApproximate.setToolTip(_translate("Dialog", "How smooth the resulting buffers will be."))
        self.label_3.setText(_translate("Dialog", "Number of Rings"))
        self.numberOfRings.setToolTip(_translate("Dialog", "Number of rings."))
        self.selectedfeats.setText(_translate("Dialog", "Buffer only selected features"))
        self.dissovle_button_2.setToolTip(_translate("Dialog", "Not dissolving may produce strange results with neighbouring features."))
        self.dissovle_button_2.setText(_translate("Dialog", "Dissolve features before buffering."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Settings"))
        self.label_5.setText(_translate("Dialog", "Buffer style:"))
        self.sequential_style.setToolTip(_translate("Dialog", "Buffer resulting buffer sequentially."))
        self.sequential_style.setText(_translate("Dialog", "Sequential"))
        self.central_style.setToolTip(_translate("Dialog", "Buffer the central feature with increasing distance."))
        self.central_style.setText(_translate("Dialog", "Central"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://rawgit.com/HeikkiVesanto/QGIS_Multi_Ring_Buffer/master/help/index.html\"><span style=\" text-decoration: underline; color:#0000ff;\">What does this mean?</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Advanced"))

