# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multi_ring_buffer_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(396, 306)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        self.label_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.mMapLayerComboBox = QgsMapLayerComboBox(Dialog)
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.horizontalLayout_4.addWidget(self.mMapLayerComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.dissovle_button_2 = QtWidgets.QCheckBox(Dialog)
        self.dissovle_button_2.setChecked(True)
        self.dissovle_button_2.setObjectName("dissovle_button_2")
        self.verticalLayout.addWidget(self.dissovle_button_2)
        self.selectedfeats = QtWidgets.QCheckBox(Dialog)
        self.selectedfeats.setEnabled(True)
        self.selectedfeats.setChecked(False)
        self.selectedfeats.setObjectName("selectedfeats")
        self.verticalLayout.addWidget(self.selectedfeats)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioRings = QtWidgets.QRadioButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioRings.sizePolicy().hasHeightForWidth())
        self.radioRings.setSizePolicy(sizePolicy)
        self.radioRings.setMinimumSize(QtCore.QSize(77, 0))
        self.radioRings.setChecked(True)
        self.radioRings.setObjectName("radioRings")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioRings)
        self.horizontalLayout.addWidget(self.radioRings)
        self.label_buf = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_buf.sizePolicy().hasHeightForWidth())
        self.label_buf.setSizePolicy(sizePolicy)
        self.label_buf.setMinimumSize(QtCore.QSize(98, 0))
        self.label_buf.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_buf.setObjectName("label_buf")
        self.horizontalLayout.addWidget(self.label_buf)
        self.bufferDistance = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bufferDistance.sizePolicy().hasHeightForWidth())
        self.bufferDistance.setSizePolicy(sizePolicy)
        self.bufferDistance.setMinimumSize(QtCore.QSize(150, 0))
        self.bufferDistance.setDecimals(10)
        self.bufferDistance.setMaximum(999999999.99)
        self.bufferDistance.setProperty("value", 10.0)
        self.bufferDistance.setObjectName("bufferDistance")
        self.horizontalLayout.addWidget(self.bufferDistance)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3_buf = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3_buf.sizePolicy().hasHeightForWidth())
        self.label_3_buf.setSizePolicy(sizePolicy)
        self.label_3_buf.setMinimumSize(QtCore.QSize(180, 0))
        self.label_3_buf.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_3_buf.setObjectName("label_3_buf")
        self.horizontalLayout_3.addWidget(self.label_3_buf)
        self.numberOfRings = QtWidgets.QSpinBox(Dialog)
        self.numberOfRings.setMinimumSize(QtCore.QSize(150, 0))
        self.numberOfRings.setMaximum(999999999)
        self.numberOfRings.setProperty("value", 5)
        self.numberOfRings.setObjectName("numberOfRings")
        self.horizontalLayout_3.addWidget(self.numberOfRings)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioDistances = QtWidgets.QRadioButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioDistances.sizePolicy().hasHeightForWidth())
        self.radioDistances.setSizePolicy(sizePolicy)
        self.radioDistances.setMinimumSize(QtCore.QSize(180, 0))
        self.radioDistances.setMaximumSize(QtCore.QSize(180, 16777215))
        self.radioDistances.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.radioDistances.setChecked(False)
        self.radioDistances.setObjectName("radioDistances")
        self.buttonGroup.addButton(self.radioDistances)
        self.horizontalLayout_7.addWidget(self.radioDistances)
        self.distancesCommaSep = QtWidgets.QLineEdit(Dialog)
        self.distancesCommaSep.setEnabled(False)
        self.distancesCommaSep.setReadOnly(False)
        self.distancesCommaSep.setObjectName("distancesCommaSep")
        self.horizontalLayout_7.addWidget(self.distancesCommaSep)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(180, 0))
        self.label_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.segmentsToApproximate = QtWidgets.QSpinBox(Dialog)
        self.segmentsToApproximate.setMinimumSize(QtCore.QSize(150, 0))
        self.segmentsToApproximate.setMaximum(300)
        self.segmentsToApproximate.setProperty("value", 25)
        self.segmentsToApproximate.setObjectName("segmentsToApproximate")
        self.horizontalLayout_2.addWidget(self.segmentsToApproximate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(0, 20, 601, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.central_style = QtWidgets.QRadioButton(self.widget)
        self.central_style.setChecked(True)
        self.central_style.setObjectName("central_style")
        self.bufferStyle = QtWidgets.QButtonGroup(Dialog)
        self.bufferStyle.setObjectName("bufferStyle")
        self.bufferStyle.addButton(self.central_style)
        self.horizontalLayout_5.addWidget(self.central_style)
        self.sequential_style = QtWidgets.QRadioButton(self.widget)
        self.sequential_style.setChecked(False)
        self.sequential_style.setObjectName("sequential_style")
        self.bufferStyle.addButton(self.sequential_style)
        self.horizontalLayout_5.addWidget(self.sequential_style)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 601, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioDonut = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioDonut.setChecked(True)
        self.radioDonut.setObjectName("radioDonut")
        self.donutGroup = QtWidgets.QButtonGroup(Dialog)
        self.donutGroup.setObjectName("donutGroup")
        self.donutGroup.addButton(self.radioDonut)
        self.horizontalLayout_6.addWidget(self.radioDonut)
        self.radioNoDonut = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioNoDonut.setChecked(False)
        self.radioNoDonut.setObjectName("radioNoDonut")
        self.donutGroup.addButton(self.radioNoDonut)
        self.horizontalLayout_6.addWidget(self.radioNoDonut)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.central_style.raise_()
        self.sequential_style.raise_()
        self.horizontalLayoutWidget.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Multi Ring Buffer"))
        self.label_4.setText(_translate("Dialog", "Layer to be buffered:"))
        self.dissovle_button_2.setToolTip(_translate("Dialog", "Attributes will not be copied to buffers. Not dissolving may produce strange results with neighbouring features"))
        self.dissovle_button_2.setText(_translate("Dialog", "Dissolve features before buffering"))
        self.selectedfeats.setText(_translate("Dialog", "Buffer only selected features"))
        self.radioRings.setText(_translate("Dialog", "Rings"))
        self.label_buf.setText(_translate("Dialog", "Buffer Distance:"))
        self.bufferDistance.setToolTip(_translate("Dialog", "Buffer distance in your selected layers CRS units"))
        self.label_3_buf.setText(_translate("Dialog", "Number of Rings:"))
        self.numberOfRings.setToolTip(_translate("Dialog", "Number of rings."))
        self.radioDistances.setToolTip(_translate("Dialog", "Raw buffer distances"))
        self.radioDistances.setText(_translate("Dialog", "Distances (comma seperated)"))
        self.distancesCommaSep.setText(_translate("Dialog", "10,20,30"))
        self.label_2.setText(_translate("Dialog", "Segments to Approximate"))
        self.segmentsToApproximate.setToolTip(_translate("Dialog", "How smooth the resulting buffers will be."))
        self.groupBox.setTitle(_translate("Dialog", "Advanced"))
        self.central_style.setToolTip(_translate("Dialog", "Buffer the central feature with increasing distance"))
        self.central_style.setText(_translate("Dialog", "Central"))
        self.sequential_style.setToolTip(_translate("Dialog", "Buffer resulting buffer sequentially"))
        self.sequential_style.setText(_translate("Dialog", "Sequential"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://rawgit.com/HeikkiVesanto/QGIS_Multi_Ring_Buffer/master/help/index.html\"><span style=\" text-decoration: underline; color:#0000ff;\">What does this mean?</span></a></p></body></html>"))
        self.radioDonut.setToolTip(_translate("Dialog", "Buffers do not contain orignal features or other buffers"))
        self.radioDonut.setText(_translate("Dialog", "Donut Ring Buffers"))
        self.radioNoDonut.setToolTip(_translate("Dialog", "Buffers contain original features and previous buffers (Central buffer style only)"))
        self.radioNoDonut.setText(_translate("Dialog", "Regular Buffers"))

from qgis.gui import QgsMapLayerComboBox
